name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
    - 'v*'

jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          willmao/fluent-bit
          registry.cn-hangzhou.aliyuncs.com/willmao/fluent-bit
        labels: |
          MAINTAINER=williamsofmao@gmail.com
          FLUENT_BIT_VERSION=2.2.2
          GO_VERSION=1.20.12
          FLUENT_BIT_GO_PLUGINS_VERSION=0.0.1
          org.opencontainers.image.created={{date 'YYYY-MM-DD HH:mm:ss' ‘Asia/Shanghai'}}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=branch
          type=ref,event=tag
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Login to Alibaba ACR
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          FLUENT_BIT_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['FLUENT_BIT_VERSION'] }}
          GO_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['GO_VERSION'] }}
          FLUENT_BIT_GO_PLUGINS_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['FLUENT_BIT_GO_PLUGINS_VERSION'] }}
