name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
    - 'v*'

jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: willmao/fluent-bit:${{github.ref_name}}

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag willmao/fluent-bit:${{github.ref_name}}
